# Generated by Django 4.1.2 on 2022-11-22 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='laptop',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
