# Generated by Django 4.1.2 on 2022-11-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0002_laptop_price_laptop_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='title',
            field=models.CharField(default='Some title here', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laptop',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
