# Generated by Django 4.1.3 on 2022-11-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0005_laptop_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='slug',
            field=models.SlugField(default=''),
        ),
    ]
