# Generated by Django 4.1.3 on 2022-12-02 21:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('laptop', '0008_laptop_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laptop.brand'),
        ),
        migrations.DeleteModel(
            name='Model',
        ),
    ]
